[manifest]
version = "0.1"
dump_lua = true
priority = 0

[[patches]]
[patches.copy]
target = "game.lua"
position = "append"
sources = [
	"src/riffraff.lua"
]

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''    self.play = CardArea(
        0, 0,
        CAI.play_W,CAI.play_H, 
        {card_limit = 5, type = 'play'})
'''
position = "after"
payload = '''    
    create_riffraff_queue()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/event.lua"
pattern = '''        achievement = {},
'''
position = "after"
payload = '''        riffraff = {},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:add_to_deck(from_debuff)
'''
position = "after"
payload = '''    if G.RIFFRAFF_QUEUE and not from_debuff and self.ability and self.ability.set == 'Joker' then
            G.RIFFRAFF_QUEUE:add_card(self)
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:apply_to_run(center)
'''
position = "after"
payload = '''    if G.RIFFRAFF_QUEUE and self and self.ability and self.ability.set == 'Voucher' then
            G.RIFFRAFF_QUEUE:add_card(self)
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:stop_hover()
'''
position = "after"
payload = '''   if self.config and self.config.riffraff_display then
        return
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.HUD:recalculate()
'''
position = "after"
payload = '''    
    clear_riffraff_queue(false)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''    G.discard.T.y = 4.2
'''
position = "after"
payload = '''    
    G.riffraff_area.T.x =  G.jokers.T.x - G.CARD_W * 1.85
    G.riffraff_area.T.y = 0
    G.riffraff_area:hard_set_VT()
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''for _, v in ipairs(info_queue) do
'''
position = "before"
payload = '''if _c.config and _c.config.riffraff_display then
    return full_UI_table
end
'''
match_indent = true
